### ISSUE TITLE
ValueError: zero-size array to reduction operation fmax which has no identity

### ISSUE THREAD

**Issue by sunqiccgk** [matthiasdemuzere/w2w#38] opened 2022-02-18 11:56 UTC
Hi，when I use the tiff from LCZ generator, I met this problem. 
I am not sure this has influence on the WRF result, but the final nc file can be used in the wrf.exe.

![c8cc296d475eb165be60c6bc59dbb84](https://user-images.githubusercontent.com/99535285/154678494-b44fe04d-9b44-485b-9697-fd4298a52f7c.png)
.

**Comment by sunqiccgk** [comment] 2022-02-21 16:39
hi @dargueso , I met another problem when I use the tiff from LCZ generator except the picture above, when I use the command in picture below, the geo_em.d02_LCZ_params.nc file I got don't have the the value from 31-41, I am wondering why this happened, could you please try the file I put below to see if the file convert right? Thank you very much!
[test.zip](https://github.com/matthiasdemuzere/w2w/files/8110861/test.zip)
![96cdac29bf9dbcac93fc2ec6d79aa74](https://user-images.githubusercontent.com/99535285/154995774-5264160b-8541-4b6d-89d4-e4ce23139d29.png)

![77138601f5ca20829a27a34d569a23c](https://user-images.githubusercontent.com/99535285/154995796-36c8edd9-6ce4-4250-9265-ac92f577cbb7.png)

![image](https://user-images.githubusercontent.com/99535285/154995881-d24e7b9c-f727-4c93-a472-07d368fe00f7.png)

**Comment by dargueso** [comment] 2022-02-21 16:54
Hi @sunqiccgk, 

I used the data you sent in the test.zip above and I get a geo_em.d02_LCZ_params.nc with LU_INDEX up to 41. Are you sure you're running the latest version?

[test_dargueso.zip](https://github.com/matthiasdemuzere/w2w/files/8110984/test_dargueso.zip)

**Comment by sunqiccgk** [comment] 2022-02-21 17:35
Hi @dargueso  that is interesting, the data from you is 40, how can I update my w2w version？ every I use :pip uninstall w2w ; then : pip install w2w ; is there sth wrong?

**Comment by sunqiccgk** [comment] 2022-02-21 17:37
last time I used : pip install git+https://github.com/matthiasdemuzere/w2w

**Comment by sunqiccgk** [comment] 2022-02-21 17:54
Hi @dargueso  I uninstall it again to make sure , and use : pip install git+https://github.com/matthiasdemuzere/w2w, try it again, the result is still 17 class.

**Comment by dargueso** [comment] 2022-02-22 10:27
Hi @sunqiccgk, I follow your steps, uninstalled and reinstalled w2w, but I'm not able to replicate your results. My resulting geo_em.d02_LCZ_params.nc has 41 classes (0-40).
I moved to the folder where the data is
I renamed your tiff to Shanghai.tif
then I run w2w ./ Shanghai.tif geo_em.d02.nc 
And I get the geo_em.d02_LCZ_params.nc with 41 categories.

Please could you double check you're looking at the right files? Just to make sure the problem is with the code. 

Also, I'm using python 3.8.5. Which version are you using? Can you send me a list of the packages you have installed in your environment?

**Comment by sunqiccgk** [comment] 2022-02-22 13:05
Hi @dargueso maybe I found the reason: I use the command :w2w -l -1 ./ Shanghai.tif  geo_em.d02.nc , but you use:  w2w ./ shanghai.tif geo_em.d02.nc ; If I don't add  -l -1, it works well. Actually I saw the user guide if you use the data from LCZ generator have to add this ?   Plus , I use python 3.9, And I try this in windows and MacOS seperately have same results.

**Comment by dargueso** [comment] 2022-02-23 08:23
Hi @sunqiccgk, 
Yes, according to the help instructions, it looks like you should use -l 1 for maps produced with the LCZ generator. 
I think @matthiasdemuzere is in a better position to clarify this since he is more familiar with the LCZ generator tool. 
Cheers,
Daniel

**Comment by matthiasdemuzere** [comment] 2022-02-23 12:52
Hi @sunqiccgk,

When using maps created by the [LCZ Generator](https://lcz-generator.rub.de/), one should indeed use the argument -l 1. As this parameter selects the band that should be read from the .tif file. That band contains the `lczFilter` map, the outcome of applying a morphological Gaussian filter on the raw LCZ map (see [Demuzere et al. (2020)](https://www.nature.com/articles/s41597-020-00605-z)) for more info.

In case you use a map produced elsewhere, I assume you only have one band in your .tif file. As such there is no need to set the -l 1 argument.

**Comment by dargueso** [comment] 2022-02-23 21:38
@sunqiccgk, I have tried running your example using -l 1 and I also get 41 categories in the  geo_em.d02_LCZ_params.nc file. It is hard to track down the error if I can't replicate your results.

I get the text below when running with -l 1:

w2w -l 1 ./ Shanghai.tif geo_em.d02.nc 
Check if LCZ domain extends WRF domain in all directions?
OK - LCZ domain is covering WRF domain

Replace WRF MODIS urban LC with surrounding natural LC

Create temporary WRF grid .tif file for resampling

+ FRC_URB2D, alter LU_INDEX, GREENFRAC and LANDUSEF

+ LCZ-based UCP values into WRF's URB_PARAM
Processing LP_URB2D ...
Processing MH_URB2D ...
Processing STDH_URB2D ...
Processing HGT_URB2D ...
Processing LB_URB2D ...
Processing LF_URB2D ...
Processing HI_URB2D ...
Working on height interval 0 - <5m ...
Working on height interval 5 - <10m ...
Working on height interval 10 - <15m ...
Working on height interval 15 - <20m ...
Working on height interval 20 - <25m ...
Working on height interval 25 - <30m ...
Working on height interval 30 - <35m ...
Working on height interval 35 - <40m ...
Working on height interval 40 - <45m ...
Working on height interval 45 - <50m ...
Working on height interval 50 - <55m ...
Working on height interval 55 - <60m ...
Working on height interval 60 - <65m ...
Working on height interval 65 - <70m ...
Working on height interval 70 - <75m ...

Create LCZ-based urban extent file (excluding other LCZ-based info).

Expanding land categories of parent domain(s) to 41:

******************************
Set nbui_max to 10 during compilation, in order to optimize memory storage.
******************************

Start sanity check and clean-up ...
Check 1: Urban class removed from geo_em.d02_NoUrban.nc?
OK

Check 2: LCZ Urban extent present in geo_em.d02_LCZ_extent.nc?
OK

Check 3: Urban LCZ classes exists in geo_em.d02_LCZ_params.nc?
OK: LCZ Classes ([1, 2, 3, 4, 5, 6, 8, 9, 10]) present

Check 4: URB_PARAMS matrix present in file geo_em.d02_LCZ_params.nc?
OK

Check 5: FRC_URB2D present in geo_em.d02_LCZ_params.nc?
OK: FRC_URB2D values range between 0.00 and 0.94

Check 6: Do URB_PARAM variable values follow expected range in geo_em.d02_LCZ_params.nc?
OK for LP_URB2D
OK for MH_URB2D
OK for HGT_URB2D
OK for LB_URB2D
OK for LF_URB2D

Check 7: Does HI_URB2D sum to 100% for urban pixels in geo_em.d02_LCZ_params.nc?
OK

Check 8: Do FRC_URB and LCZs (from LU_INDEX) cover same extent in geo_em.d02_LCZ_params.nc?
OK

Check 9: Extent and # urban pixels same for *_extent.nc and *_params.nc output file?
OK, urban extent the same. 
Both files have 3622 urban pixels according to LU_INDEX

Cleaning up ...

********* All done ***********

**Comment by matthiasdemuzere** [comment] 2022-02-24 08:43
Hi @sunqiccgk,

As you are using an older file from the WUDAPT portal, that contains LCZ classes 101-107 and is not using EPSG:4326 as coordinate system, I have changed the code so that these two elements are taken care off.

You can install this update with: `pip install --upgrade --force-reinstall git+https://github.com/matthiasdemuzere/w2w.git`

Testing this version on your previously provided Shanghai.tif and geo_em.d01 and 02.nc files:

`w2w YOUUR_FOLDER/ Shanghai.tif geo_em.d02.nc`

Works for me.

See output here: 
[w2w_output_Shanghai.zip](https://github.com/matthiasdemuzere/w2w/files/8130947/w2w_output_Shanghai.zip)

**Comment by sunqiccgk** [comment] 2022-02-28 14:34
Hi @dargueso ,thanks for your response, maybe  some packages influence  the results? I use ubuntu and use miniconda3, python3.9.1 and gcc 7.3.0
if you need further information to find where is the problem, please tell me and  I will check it.
Thanks for you sincere help!

**Comment by sunqiccgk** [comment] 2022-02-28 14:39
hi @matthiasdemuzere ,thanks for you help! Actually the data I used just download directly from WUDAPT website and  I plot the map using Arcmap , there are three band actually. 
Thanks for changing the code which can be used for an older file.

**Comment by matthiasdemuzere** [comment] 2022-03-01 14:16
> hi @matthiasdemuzere ,thanks for you help! Actually the data I used just download directly from WUDAPT website and I plot the map using Arcmap , there are three band actually. Thanks for changing the code which can be used for an older file.

The .tif file I got from you (see also attached), only contains 1 band. So to me it is not clear what file you are using ..
[Shanghai.zip](https://github.com/matthiasdemuzere/w2w/files/8162173/Shanghai.zip)
.

**Comment by matthiasdemuzere** [comment] 2022-03-09 17:57
All seems resolved with recent updates, closing this now.

**Closed by matthiasdemuzere** 2022-03-09 17:57 UTC
