### ISSUE TITLE
w2w error with lcz

### ISSUE THREAD

**Issue by fipoucat** [matthiasdemuzere/w2w#93] opened 2022-09-17 14:10 UTC
I am using an lcz image with the right dimension but getting an error during the processing:

ERROR 1: PROJ: proj_create_from_name: /usr/local/anaconda3/share/proj/proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR / DATABASE.LAYOUT.VERSION.MINOR metadata. It comes from another PROJ installation.
--> Replace WRF MODIS urban LC with surrounding natural LC
Looping through urban grid pixels: 100%|███████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 93.86it/s]
--> Create LCZ-based geo_em file
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/w2w", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 179, in main
    nbui_max = create_lcz_params_file(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 1226, in create_lcz_params_file
    dst_data = _add_frc_lu_index_2_wrf(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 1152, in _add_frc_lu_index_2_wrf
    frc_urb = _ucp_resampler(
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 675, in _ucp_resampler
    wrf_grid_info = _get_wrf_grid_info(info)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/w2w/w2w.py", line 618, in _get_wrf_grid_info
    'crs': wrf_proj.to_proj4(),
AttributeError: 'Proj' object has no attribute 'to_proj4'

**Comment by theendlessriver13** [comment] 2022-09-17 14:41
duplicate of #77 which you even opened yourself less than 2 month ago!

Please search the issue tracker first and then also please use the provided issue template - it's there for a reason! Like last time, without being able see your computer, we need more information about your environment, installed packages and what exactly you are doing with what kind of input (if relevant and not reproducible with the example data).

**Closed by theendlessriver13** 2022-09-17 14:41 UTC
